apiVersion: v1
kind: Namespace
metadata:
  name: rook-cockroachdb
---
apiVersion: cockroachdb.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cockroachdb
  namespace: rook-cockroachdb
spec:
  scope:
  secure: false
  replicas: 3
  volumeSize: 1Gi
  cachePercent: 25
  maxSQLMemoryPercent: 25